version: '3.2'

services:
  postgres:
    image: postgres
    container_name: postgresSql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data